spring:

  datasource:
    url: jdbc:h2:~/testDB;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:

      client:
        registration:
          google:
            client-id: ${google_client_id}
            client-secret: ${google_client_secret}
            scope:
              - email
              - profile
          facebook:
            client-id: ${facebook_client_id}
            client-secret: ${facebook_client_secret}
            scope:
              - email
              - public_profile
          naver:
            client-id: ${naver_client_id}
            client-secret: ${naver_client_secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - nickname
              - email
              - profile_image
            client-name: Naver
          kakao:
            authorization-grant-type: authorization_code
            client-id: ${kakao_client_id}
            client-secret: ${kakao_client_secret}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile
              - account_email
            client-authentication-method: POST
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: properties
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    org.apache.coyote.http11: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace