logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSSXXX}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr([%X{TraceId}]){magenta} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google_client_id}
            client-secret: ${google_client_secret}
            scope:
              - email
              - profile
          facebook:
            client-id: ${facebook_client_id}
            client-secret: ${facebook_client_secret}
            scope:
              - email
              - public_profile
          naver:
            client-id: ${naver_client_id}
            client-secret: ${naver_client_secret}
            scope:
              - nickname
              - email
              - profile_image
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Naver
          kakao:
            client-id: ${kakao_client_id}
            client-secret: ${kakao_client_secret}
            scope:
              - profile
              - account_email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Kakao
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: properties
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response